spring:
  application.name: secret-stash
  main.banner-mode: off
  threads.virtual.enabled: true
  mvc.problemdetails.enabled: true

jwt:
  # A random key ID to sign JWT. Can be rotated by changing this property.
  key-id: 3187aa78-0072-4c54-b87c-34687c573167
  issuer: http://localhost:8080
  token-expiration: 1h

public:
  host:
  expiration-time: 1h

ratelimit:
  period: 1s
  user-limit: 60
  global-limit: 1000


logging:
  level:
    com.ivansuvorov: DEBUG